[project]
name = "i-AOMA"
version = "2.0.0"
description = "intelligent Automatic Operational Modal Analysis"
authors = [
    {name = "Marco Martino Rosso", email = "marco.rosso@polito.it"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "GPL"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
